package ui.main;


import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;


import model.Employee;
import model.Manager;
import model.Order;
import service.EmployeeService;
import staticProcess.StaticProcess;
import ui.login.Login;
import ui.table.TableCustom;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;


public class TodayRevenueStatistic extends javax.swing.JPanel {

    public TodayRevenueStatistic() throws MalformedURLException, NotBoundException, RemoteException {
        initComponents();

        setupTable();
        TableCustom.apply(scrollPane_tableCustomer, TableCustom.TableType.MULTI_LINE);

        String role = "";
        if(!Login.checkRole()){
            Manager manager = Login.getManagerLogin();
            if(manager != null){
                role = manager.getManagerID();
            }
        } else {
            Employee employee = Login.getEmployeeLogin();
            if(employee != null){
                role = employee.getEmployeeID();

//                ArrayList<Order> orderList = new OrderDAO(Order.class).filterOrderByEmpID(role);
//                for (Order o : orderList){
//                    DefaultTableModel model = (DefaultTableModel) tableStatictis.getModel();
//                    model.addRow(new Object[]{o.getOrderID(), o.getCustomer().getCustomerName(), o.getEmployee().getEmployeeName(), o.getOrderDate()
//                            , o.getPrescription() == null ?"": o.getPrescription().getPrescriptionID()
//                            , o.getDiscount(), o.getTotalDue() });
//                }
//                lblSum_number.setText(StaticProcess.df.format(new OrderDAO(Order.class).calculateTotalAllOrder(role)));
//                repaint();
            }

            Employee employ = ((EmployeeService)Naming.lookup("rmi://localhost:7281/employeeService")).findById(role);
            if(employ != null){
                lblEmpID_show.setText(role);
                lblEmpName_show.setText(employee.getEmployeeName());
            }
        }



    }

    private void setupTable() {
        JTableHeader theader = tableStatictis.getTableHeader();
        theader.setFont(new java.awt.Font("Segoe UI", 0, 18));
        tableStatictis.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        if (tableStatictis.getColumnModel().getColumnCount() > 0) {
            tableStatictis.getColumnModel().getColumn(0).setPreferredWidth(200);
            tableStatictis.getColumnModel().getColumn(1).setPreferredWidth(250);
            tableStatictis.getColumnModel().getColumn(2).setPreferredWidth(250);
            tableStatictis.getColumnModel().getColumn(3).setPreferredWidth(250);
            tableStatictis.getColumnModel().getColumn(4).setPreferredWidth(150);
            tableStatictis.getColumnModel().getColumn(5).setPreferredWidth(182);
            tableStatictis.getColumnModel().getColumn(6).setPreferredWidth(200);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        pCenter = new javax.swing.JPanel();
        scrollPane_tableCustomer = new javax.swing.JScrollPane();
        tableStatictis = new JTable();
        lbTitlePane = new javax.swing.JLabel();
        lblEmpName_show = new javax.swing.JLabel();
        lblEmpID_show = new javax.swing.JLabel();
        lblEmpID = new javax.swing.JLabel();
        lblEmpName = new javax.swing.JLabel();
        lblSum_number = new javax.swing.JLabel();
        lblSum = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1620, 1000));
        setLayout(new java.awt.BorderLayout());

        pCenter.setBackground(new java.awt.Color(242, 249, 255));
        pCenter.setPreferredSize(new java.awt.Dimension(1600, 1000));

        scrollPane_tableCustomer.setBackground(new java.awt.Color(221, 221, 221));
        scrollPane_tableCustomer.setBorder(null);

        tableStatictis.setBackground(new java.awt.Color(221, 221, 221));
        tableStatictis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableStatictis.setModel(new DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Mã hóa đơn", "Khách hàng", "Người tạo", "Thời gian", "Hình thức", "Khuyến mãi", "Tổng tiền"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableStatictis.setGridColor(new java.awt.Color(218, 247, 249));
        scrollPane_tableCustomer.setViewportView(tableStatictis);

        lbTitlePane.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbTitlePane.setForeground(new java.awt.Color(102, 204, 255));
        lbTitlePane.setText("THỐNG KÊ DOANH THU");

        lblEmpName_show.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        lblEmpID_show.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        lblEmpID.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblEmpID.setText("Mã nhân viên:");

        lblEmpName.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblEmpName.setText("Họ và tên:");

        lblSum_number.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblSum_number.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblSum.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblSum.setText("Tổng tiền");

        javax.swing.GroupLayout pCenterLayout = new javax.swing.GroupLayout(pCenter);
        pCenter.setLayout(pCenterLayout);
        pCenterLayout.setHorizontalGroup(
                pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pCenterLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(scrollPane_tableCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 1482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(70, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCenterLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCenterLayout.createSequentialGroup()
                                                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(pCenterLayout.createSequentialGroup()
                                                                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(lblEmpName)
                                                                        .addComponent(lblEmpID))
                                                                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(pCenterLayout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(lblEmpName_show))
                                                                        .addGroup(pCenterLayout.createSequentialGroup()
                                                                                .addGap(77, 77, 77)
                                                                                .addComponent(lblEmpID_show)))
                                                                .addGap(19, 19, 19))
                                                        .addComponent(lbTitlePane))
                                                .addGap(597, 597, 597))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCenterLayout.createSequentialGroup()
                                                .addComponent(lblSum, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblSum_number, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(62, 62, 62))))
        );
        pCenterLayout.setVerticalGroup(
                pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pCenterLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lbTitlePane, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblEmpID_show)
                                        .addComponent(lblEmpID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblEmpName)
                                        .addComponent(lblEmpName_show))
                                .addGap(84, 84, 84)
                                .addComponent(scrollPane_tableCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblSum)
                                        .addComponent(lblSum_number))
                                .addGap(97, 97, 97))
        );

        add(pCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>



    // Variables declaration - do not modify
    private javax.swing.JLabel lbTitlePane;
    private javax.swing.JLabel lblEmpID;
    private javax.swing.JLabel lblEmpID_show;
    private javax.swing.JLabel lblEmpName;
    private javax.swing.JLabel lblEmpName_show;
    private javax.swing.JLabel lblSum;
    private javax.swing.JLabel lblSum_number;
    private javax.swing.JPanel pCenter;
    private javax.swing.JScrollPane scrollPane_tableCustomer;
    private JTable tableStatictis;
    // End of variables declaration
}

